services:
  prometheus:
    image: prom/prometheus:v2.35.0
    ports:
      - 9000:9090
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml